"""Drop movies column from users table

Revision ID: 7dd4d1d3ebfc
Revises: 9f6ab71434c5
Create Date: 2025-06-23 15:58:26.162944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd4d1d3ebfc'
down_revision: Union[str, Sequence[str], None] = '9f6ab71434c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
