"""Add movies column to users table

Revision ID: 9f6ab71434c5
Revises: 3dd693552806
Create Date: 2025-06-23 15:57:15.073881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6ab71434c5'
down_revision: Union[str, Sequence[str], None] = '3dd693552806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'movies')
    op.add_column('users', sa.Column('movies', sa.String(), nullable=True, comment='Movies associated with the category'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'movies')
    op.add_column('categories', sa.Column('movies', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Movies associated with the category'))
    # ### end Alembic commands ###
