"""Drop movies column from users table

Revision ID: a7adce073c79
Revises: 7dd4d1d3ebfc
Create Date: 2025-06-23 15:59:49.598240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7adce073c79'
down_revision: Union[str, Sequence[str], None] = '7dd4d1d3ebfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('movies', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Movies associated with the category'))
    # ### end Alembic commands ###
